/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salesberry;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import InventoryManagementSystem.DatabasePackage;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author amrit
 */
public class Sales extends javax.swing.JFrame {
    Connection con = DatabasePackage.getConnection();
    CallableStatement csmt = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form Homepage
     */
    public Sales() {
        initComponents();
       Toolkit toolkit=getToolkit();
Dimension size=toolkit.getScreenSize();
setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
tabl();
    }

    public void tabl(){
           try{ 
            String sql ="select * from sales";
            ps = con.prepareStatement(sql);
            rs=ps.executeQuery();
         custable.setModel(DbUtils.resultSetToTableModel(rs));//custable= name of the table
        }
    
     catch(Exception e){

}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body_Panel = new javax.swing.JPanel();
        SalesBerryText_Panel = new javax.swing.JPanel();
        SalesBerry_Logo_Text = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        custable = new javax.swing.JTable();
        home = new javax.swing.JButton();
        Sales_Panel = new javax.swing.JPanel();
        Sales_Button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        customer_name = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        customer_phone = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        sales_product = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        add_button3 = new javax.swing.JButton();
        clr_button3 = new javax.swing.JButton();
        dlt_button3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        sales_qty = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        sales_date = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        CustSupplierID = new javax.swing.JTextPane();
        MenuBar = new javax.swing.JMenuBar();
        SetupMenu = new javax.swing.JMenu();
        Category = new javax.swing.JMenuItem();
        Unit = new javax.swing.JMenuItem();
        Product = new javax.swing.JMenuItem();
        Customer = new javax.swing.JMenuItem();
        Supplier = new javax.swing.JMenuItem();
        TransactionMenu = new javax.swing.JMenu();
        PurchaseTransaction = new javax.swing.JMenuItem();
        SalesTransaction = new javax.swing.JMenuItem();
        ReportsMenu = new javax.swing.JMenu();
        PurchaseReport = new javax.swing.JMenuItem();
        SalesReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Body_Panel.setBackground(new java.awt.Color(211, 239, 236));
        Body_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Body_Panel.setForeground(new java.awt.Color(0, 102, 102));

        SalesBerryText_Panel.setBackground(new java.awt.Color(211, 239, 236));

        SalesBerry_Logo_Text.setBackground(new java.awt.Color(0, 153, 153));
        SalesBerry_Logo_Text.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        SalesBerry_Logo_Text.setForeground(new java.awt.Color(0, 102, 102));
        SalesBerry_Logo_Text.setText("SalesBerry");

        javax.swing.GroupLayout SalesBerryText_PanelLayout = new javax.swing.GroupLayout(SalesBerryText_Panel);
        SalesBerryText_Panel.setLayout(SalesBerryText_PanelLayout);
        SalesBerryText_PanelLayout.setHorizontalGroup(
            SalesBerryText_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalesBerryText_PanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(SalesBerry_Logo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        SalesBerryText_PanelLayout.setVerticalGroup(
            SalesBerryText_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesBerryText_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalesBerry_Logo_Text)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        custable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sales ID", "Customer Name", "Customer Phone", "Sales Date", "Sales Product", "Sales Quantity", "Entered By"
            }
        ));
        jScrollPane5.setViewportView(custable);

        home.setBackground(new java.awt.Color(0, 102, 102));
        home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        Sales_Panel.setBackground(new java.awt.Color(204, 204, 255));
        Sales_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Sales_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/Sales.jpg"))); // NOI18N
        Sales_Button.setBorder(null);
        Sales_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sales_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sales_PanelLayout = new javax.swing.GroupLayout(Sales_Panel);
        Sales_Panel.setLayout(Sales_PanelLayout);
        Sales_PanelLayout.setHorizontalGroup(
            Sales_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sales_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sales_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Sales_PanelLayout.setVerticalGroup(
            Sales_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sales_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sales_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(211, 239, 236));

        jScrollPane11.setViewportView(customer_name);

        jLabel9.setText("Customer Name:");

        jLabel10.setText("Phone:");

        jScrollPane12.setViewportView(customer_phone);

        jLabel11.setText("Product:");

        jScrollPane13.setViewportView(sales_product);

        jPanel7.setBackground(new java.awt.Color(211, 239, 236));

        add_button3.setBackground(new java.awt.Color(0, 102, 102));
        add_button3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_button3.setForeground(new java.awt.Color(255, 255, 255));
        add_button3.setText("SUBMIT");
        add_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_button3ActionPerformed(evt);
            }
        });

        clr_button3.setBackground(new java.awt.Color(0, 102, 102));
        clr_button3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clr_button3.setForeground(new java.awt.Color(255, 255, 255));
        clr_button3.setText("CLEAR");
        clr_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_button3ActionPerformed(evt);
            }
        });

        dlt_button3.setBackground(new java.awt.Color(0, 102, 102));
        dlt_button3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dlt_button3.setForeground(new java.awt.Color(255, 255, 255));
        dlt_button3.setText("DELETE");
        dlt_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(add_button3)
                .addGap(18, 18, 18)
                .addComponent(clr_button3)
                .addGap(18, 18, 18)
                .addComponent(dlt_button3)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button3)
                    .addComponent(clr_button3)
                    .addComponent(dlt_button3))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel4.setText("Qty:");

        jScrollPane6.setViewportView(sales_qty);

        jLabel12.setText("Date:");

        jScrollPane14.setViewportView(sales_date);

        jLabel13.setText("Entered By (ID):");

        jScrollPane15.setViewportView(CustSupplierID);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(18, 363, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6))))
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(6, 6, 6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Body_PanelLayout = new javax.swing.GroupLayout(Body_Panel);
        Body_Panel.setLayout(Body_PanelLayout);
        Body_PanelLayout.setHorizontalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(home)
                        .addGap(84, 84, 84)
                        .addComponent(SalesBerryText_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sales_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Body_PanelLayout.setVerticalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalesBerryText_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sales_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(home)))
                .addGap(19, 19, 19)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        MenuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        SetupMenu.setBackground(new java.awt.Color(0, 51, 51));
        SetupMenu.setText("Setup");

        Category.setText("Category");
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        SetupMenu.add(Category);

        Unit.setText("Unit");
        Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitActionPerformed(evt);
            }
        });
        SetupMenu.add(Unit);

        Product.setText("Product");
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        SetupMenu.add(Product);

        Customer.setText("Customer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        SetupMenu.add(Customer);

        Supplier.setText("Supplier");
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });
        SetupMenu.add(Supplier);

        MenuBar.add(SetupMenu);

        TransactionMenu.setText("Transaction");

        PurchaseTransaction.setText("Purchase");
        PurchaseTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseTransactionActionPerformed(evt);
            }
        });
        TransactionMenu.add(PurchaseTransaction);

        SalesTransaction.setText("Sales");
        TransactionMenu.add(SalesTransaction);

        MenuBar.add(TransactionMenu);

        ReportsMenu.setText("Reports");

        PurchaseReport.setText("Purchase Report");
        PurchaseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseReportActionPerformed(evt);
            }
        });
        ReportsMenu.add(PurchaseReport);

        SalesReport.setText("Sales Report");
        SalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesReportActionPerformed(evt);
            }
        });
        ReportsMenu.add(SalesReport);

        MenuBar.add(ReportsMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Body_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PurchaseTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseTransactionActionPerformed
Sales as=new Sales();
as.setVisible(true);
this.dispose();
    }//GEN-LAST:event_PurchaseTransactionActionPerformed

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
Category solld=new Category();
solld.setVisible(true);
this.dispose();
    }//GEN-LAST:event_CategoryActionPerformed

    private void SalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesReportActionPerformed
SalesReports akq=new SalesReports();
akq.setVisible(true);
this.dispose();
    }//GEN-LAST:event_SalesReportActionPerformed

    private void PurchaseReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseReportActionPerformed
PurchaseReports ak=new PurchaseReports();
ak.setVisible(true);
this.dispose();
    }//GEN-LAST:event_PurchaseReportActionPerformed

    private void UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitActionPerformed
Unit asee=new Unit();
asee.setVisible(true);
this.dispose();
    }//GEN-LAST:event_UnitActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
Product fa=new Product();
fa.setVisible(true);
this.dispose();
    }//GEN-LAST:event_ProductActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
Customer faa=new Customer();
faa.setVisible(true);
this.dispose();
    }//GEN-LAST:event_CustomerActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Homepage ako=new Homepage();
        ako.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void Sales_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sales_ButtonActionPerformed
        Sales sold=new Sales();
        sold.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Sales_ButtonActionPerformed

    private void add_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_button3ActionPerformed
        try {
            String sql = "insert into sales"
            +"(customer_name, customer_phone, sales_date, sales_product, sales_qty, CustSupplierID)"
            +"values (?,?,?,?,?,?)";
            ps = con.prepareStatement(sql);
            ps.setString(1, customer_name.getText());
            ps.setString(2, customer_phone.getText());
            ps.setString(3, sales_date.getText());
            ps.setString(4, sales_product.getText());
            ps.setString(5, sales_qty.getText());
            ps.setString(6, CustSupplierID.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Sales Product Successfully Added!");

            //rs.close();
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        new Sales().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_button3ActionPerformed

    private void clr_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_button3ActionPerformed

        customer_name.setText("");
        customer_phone.setText("");
        sales_date.setText("");
        sales_product.setText("");
        sales_qty.setText("");
        CustSupplierID.setText("");
    }//GEN-LAST:event_clr_button3ActionPerformed

    private void dlt_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_button3ActionPerformed
        //delete  option
        int row=custable.getSelectedRow();
        String ch= custable.getModel().getValueAt(row,0).toString();
        String sql = "DELETE FROM `sales` WHERE sales_id ="+ch;
        try {
            ps=con.prepareStatement(sql);
            ps.execute();
            int response= JOptionPane.showConfirmDialog(this,"Do you want to delete ?","confirm",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(response==JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(this,"sucessfully delete");

            }
            tabl();
        } catch(Exception  e){
            JOptionPane.showMessageDialog(this,"unable to  delete");

        }
    }//GEN-LAST:event_dlt_button3ActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
Supplier faas=new Supplier();
faas.setVisible(true);
this.dispose();
    }//GEN-LAST:event_SupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body_Panel;
    private javax.swing.JMenuItem Category;
    private javax.swing.JTextPane CustSupplierID;
    private javax.swing.JMenuItem Customer;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Product;
    private javax.swing.JMenuItem PurchaseReport;
    private javax.swing.JMenuItem PurchaseTransaction;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JPanel SalesBerryText_Panel;
    private javax.swing.JLabel SalesBerry_Logo_Text;
    private javax.swing.JMenuItem SalesReport;
    private javax.swing.JMenuItem SalesTransaction;
    private javax.swing.JButton Sales_Button;
    private javax.swing.JPanel Sales_Panel;
    private javax.swing.JMenu SetupMenu;
    private javax.swing.JMenuItem Supplier;
    private javax.swing.JMenu TransactionMenu;
    private javax.swing.JMenuItem Unit;
    private javax.swing.JButton add_button3;
    private javax.swing.JButton clr_button3;
    private javax.swing.JTable custable;
    private javax.swing.JTextPane customer_name;
    private javax.swing.JTextPane customer_phone;
    private javax.swing.JButton dlt_button3;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane sales_date;
    private javax.swing.JTextPane sales_product;
    private javax.swing.JTextPane sales_qty;
    // End of variables declaration//GEN-END:variables
}
