/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salesberry;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import InventoryManagementSystem.DatabasePackage;
/**
 *
 * @author amrit
 */
public class Homepage extends javax.swing.JFrame {
    Connection con = DatabasePackage.getConnection();
    CallableStatement csmt = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
       Toolkit toolkit=getToolkit();
Dimension size=toolkit.getScreenSize();
setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body_Panel = new javax.swing.JPanel();
        Welcome_Text = new javax.swing.JLabel();
        Sales_Panel = new javax.swing.JPanel();
        Sales_Button = new javax.swing.JButton();
        Purchase_Panel = new javax.swing.JPanel();
        Purchase_Button = new javax.swing.JButton();
        SalesReport_Panel = new javax.swing.JPanel();
        SalesReport_Button = new javax.swing.JButton();
        Inventory_Panel = new javax.swing.JPanel();
        Inventory_Button = new javax.swing.JButton();
        Feedback_Panel = new javax.swing.JPanel();
        Feedback_Button = new javax.swing.JButton();
        User_Panel = new javax.swing.JPanel();
        User_Button = new javax.swing.JButton();
        SalesBerryText_Panel = new javax.swing.JPanel();
        SalesBerry_Logo_Text = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        SetupMenu = new javax.swing.JMenu();
        Category = new javax.swing.JMenuItem();
        Unit = new javax.swing.JMenuItem();
        Product = new javax.swing.JMenuItem();
        Customer = new javax.swing.JMenuItem();
        Supplier = new javax.swing.JMenuItem();
        TransactionMenu = new javax.swing.JMenu();
        PurchaseTransaction = new javax.swing.JMenuItem();
        SalesTransaction = new javax.swing.JMenuItem();
        ReportsMenu = new javax.swing.JMenu();
        PurchaseReport = new javax.swing.JMenuItem();
        SalesReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Body_Panel.setBackground(new java.awt.Color(211, 239, 236));
        Body_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Body_Panel.setForeground(new java.awt.Color(0, 102, 102));

        Welcome_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Welcome_Text.setForeground(new java.awt.Color(0, 153, 153));
        Welcome_Text.setText("Welcome to SalesBerry Homepage!");

        Sales_Panel.setBackground(new java.awt.Color(204, 204, 255));
        Sales_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Sales_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/Sales.jpg"))); // NOI18N
        Sales_Button.setBorder(null);
        Sales_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sales_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sales_PanelLayout = new javax.swing.GroupLayout(Sales_Panel);
        Sales_Panel.setLayout(Sales_PanelLayout);
        Sales_PanelLayout.setHorizontalGroup(
            Sales_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sales_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sales_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Sales_PanelLayout.setVerticalGroup(
            Sales_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sales_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sales_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Purchase_Panel.setBackground(new java.awt.Color(204, 204, 255));
        Purchase_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Purchase_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/Purchase.jpg"))); // NOI18N
        Purchase_Button.setBorder(null);
        Purchase_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Purchase_PanelLayout = new javax.swing.GroupLayout(Purchase_Panel);
        Purchase_Panel.setLayout(Purchase_PanelLayout);
        Purchase_PanelLayout.setHorizontalGroup(
            Purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Purchase_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Purchase_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Purchase_PanelLayout.setVerticalGroup(
            Purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Purchase_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Purchase_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SalesReport_Panel.setBackground(new java.awt.Color(204, 204, 255));
        SalesReport_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        SalesReport_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/SalesReports.jpg"))); // NOI18N
        SalesReport_Button.setBorder(null);
        SalesReport_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesReport_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SalesReport_PanelLayout = new javax.swing.GroupLayout(SalesReport_Panel);
        SalesReport_Panel.setLayout(SalesReport_PanelLayout);
        SalesReport_PanelLayout.setHorizontalGroup(
            SalesReport_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesReport_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalesReport_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        SalesReport_PanelLayout.setVerticalGroup(
            SalesReport_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesReport_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalesReport_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Inventory_Panel.setBackground(new java.awt.Color(204, 204, 255));
        Inventory_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Inventory_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/Inventory.png"))); // NOI18N
        Inventory_Button.setBorder(null);
        Inventory_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventory_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inventory_PanelLayout = new javax.swing.GroupLayout(Inventory_Panel);
        Inventory_Panel.setLayout(Inventory_PanelLayout);
        Inventory_PanelLayout.setHorizontalGroup(
            Inventory_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inventory_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Inventory_PanelLayout.setVerticalGroup(
            Inventory_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inventory_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Feedback_Panel.setBackground(new java.awt.Color(204, 204, 255));
        Feedback_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Feedback_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/Feedback.jpg"))); // NOI18N
        Feedback_Button.setBorder(null);
        Feedback_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feedback_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Feedback_PanelLayout = new javax.swing.GroupLayout(Feedback_Panel);
        Feedback_Panel.setLayout(Feedback_PanelLayout);
        Feedback_PanelLayout.setHorizontalGroup(
            Feedback_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Feedback_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Feedback_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        Feedback_PanelLayout.setVerticalGroup(
            Feedback_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Feedback_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Feedback_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        User_Panel.setBackground(new java.awt.Color(204, 204, 255));
        User_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        User_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryManagementSystem/User Login.jpg"))); // NOI18N
        User_Button.setBorder(null);
        User_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout User_PanelLayout = new javax.swing.GroupLayout(User_Panel);
        User_Panel.setLayout(User_PanelLayout);
        User_PanelLayout.setHorizontalGroup(
            User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(User_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        User_PanelLayout.setVerticalGroup(
            User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(User_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SalesBerryText_Panel.setBackground(new java.awt.Color(211, 239, 236));

        SalesBerry_Logo_Text.setBackground(new java.awt.Color(0, 153, 153));
        SalesBerry_Logo_Text.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        SalesBerry_Logo_Text.setForeground(new java.awt.Color(0, 102, 102));
        SalesBerry_Logo_Text.setText("SalesBerry");

        javax.swing.GroupLayout SalesBerryText_PanelLayout = new javax.swing.GroupLayout(SalesBerryText_Panel);
        SalesBerryText_Panel.setLayout(SalesBerryText_PanelLayout);
        SalesBerryText_PanelLayout.setHorizontalGroup(
            SalesBerryText_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesBerryText_PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SalesBerry_Logo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        SalesBerryText_PanelLayout.setVerticalGroup(
            SalesBerryText_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalesBerryText_PanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(SalesBerry_Logo_Text)
                .addContainerGap())
        );

        javax.swing.GroupLayout Body_PanelLayout = new javax.swing.GroupLayout(Body_Panel);
        Body_Panel.setLayout(Body_PanelLayout);
        Body_PanelLayout.setHorizontalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SalesBerryText_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sales_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalesReport_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Purchase_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inventory_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Feedback_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(User_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Welcome_Text)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        Body_PanelLayout.setVerticalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalesBerryText_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Welcome_Text)
                .addGap(31, 31, 31)
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Feedback_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Purchase_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sales_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalesReport_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventory_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        MenuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        SetupMenu.setBackground(new java.awt.Color(0, 51, 51));
        SetupMenu.setText("Setup");

        Category.setText("Category");
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        SetupMenu.add(Category);

        Unit.setText("Unit");
        Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitActionPerformed(evt);
            }
        });
        SetupMenu.add(Unit);

        Product.setText("Product");
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        SetupMenu.add(Product);

        Customer.setText("Customer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        SetupMenu.add(Customer);

        Supplier.setText("Supplier");
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });
        SetupMenu.add(Supplier);

        MenuBar.add(SetupMenu);

        TransactionMenu.setText("Transaction");

        PurchaseTransaction.setText("Purchase");
        PurchaseTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseTransactionActionPerformed(evt);
            }
        });
        TransactionMenu.add(PurchaseTransaction);

        SalesTransaction.setText("Sales");
        TransactionMenu.add(SalesTransaction);

        MenuBar.add(TransactionMenu);

        ReportsMenu.setText("Reports");

        PurchaseReport.setText("Purchase Report");
        PurchaseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseReportActionPerformed(evt);
            }
        });
        ReportsMenu.add(PurchaseReport);

        SalesReport.setText("Sales Report");
        SalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesReportActionPerformed(evt);
            }
        });
        ReportsMenu.add(SalesReport);

        MenuBar.add(ReportsMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PurchaseTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseTransactionActionPerformed
Purchase as=new Purchase();
as.setVisible(true);
this.dispose();
    }//GEN-LAST:event_PurchaseTransactionActionPerformed

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
Category solsld=new Category();
solsld.setVisible(true);
this.dispose();
    }//GEN-LAST:event_CategoryActionPerformed

    private void Sales_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sales_ButtonActionPerformed
Sales sbld=new Sales();
sbld.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Sales_ButtonActionPerformed

    private void Purchase_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_ButtonActionPerformed
Purchase ags=new Purchase();
ags.setVisible(true);
this.dispose();
    }//GEN-LAST:event_Purchase_ButtonActionPerformed

    private void Feedback_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feedback_ButtonActionPerformed
Feedback akas=new Feedback();
akas.setVisible(true);
this.dispose();
    }//GEN-LAST:event_Feedback_ButtonActionPerformed

    private void SalesReport_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesReport_ButtonActionPerformed
SalesReports akqw=new SalesReports();
akqw.setVisible(true);
this.dispose();
    }//GEN-LAST:event_SalesReport_ButtonActionPerformed

    private void Inventory_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventory_ButtonActionPerformed
Inventory akgrk=new Inventory();
akgrk.setVisible(true);
this.dispose();
    }//GEN-LAST:event_Inventory_ButtonActionPerformed

    private void User_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_ButtonActionPerformed
UserLogin asdf=new UserLogin();
asdf.setVisible(true);
this.dispose();
    }//GEN-LAST:event_User_ButtonActionPerformed

    private void SalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesReportActionPerformed
SalesReports akeq=new SalesReports();
akeq.setVisible(true);
this.dispose();
    }//GEN-LAST:event_SalesReportActionPerformed

    private void PurchaseReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseReportActionPerformed
PurchaseReports akl=new PurchaseReports();
akl.setVisible(true);
this.dispose();
    }//GEN-LAST:event_PurchaseReportActionPerformed

    private void UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitActionPerformed
Unit aseeo=new Unit();
aseeo.setVisible(true);
this.dispose();
    }//GEN-LAST:event_UnitActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
Product fan=new Product();
fan.setVisible(true);
this.dispose();
    }//GEN-LAST:event_ProductActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
Customer faar=new Customer();
faar.setVisible(true);
this.dispose();
    }//GEN-LAST:event_CustomerActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
Supplier faast=new Supplier();
faast.setVisible(true);
this.dispose();
    }//GEN-LAST:event_SupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body_Panel;
    private javax.swing.JMenuItem Category;
    private javax.swing.JMenuItem Customer;
    private javax.swing.JButton Feedback_Button;
    private javax.swing.JPanel Feedback_Panel;
    private javax.swing.JButton Inventory_Button;
    private javax.swing.JPanel Inventory_Panel;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Product;
    private javax.swing.JMenuItem PurchaseReport;
    private javax.swing.JMenuItem PurchaseTransaction;
    private javax.swing.JButton Purchase_Button;
    private javax.swing.JPanel Purchase_Panel;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JPanel SalesBerryText_Panel;
    private javax.swing.JLabel SalesBerry_Logo_Text;
    private javax.swing.JMenuItem SalesReport;
    private javax.swing.JButton SalesReport_Button;
    private javax.swing.JPanel SalesReport_Panel;
    private javax.swing.JMenuItem SalesTransaction;
    private javax.swing.JButton Sales_Button;
    private javax.swing.JPanel Sales_Panel;
    private javax.swing.JMenu SetupMenu;
    private javax.swing.JMenuItem Supplier;
    private javax.swing.JMenu TransactionMenu;
    private javax.swing.JMenuItem Unit;
    private javax.swing.JButton User_Button;
    private javax.swing.JPanel User_Panel;
    private javax.swing.JLabel Welcome_Text;
    // End of variables declaration//GEN-END:variables
}
